[tool.bumpversion]
current_version = "1.4.0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = false
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
commit = false
message = "Bump version: {current_version} → {new_version}"
commit_args = ""
setup_hooks = []
pre_commit_hooks = []
post_commit_hooks = []


[[tool.bumpversion.files]]
filename = "VERSION"

[[tool.bumpversion.files]]
filename = 'pyproject.toml'
search = "{current_version}"
replace = "{new_version}"

[[tool.bumpversion.files]]
filename = 'tests/__init__.py'
search = "__date__ = \"\\d{{4}}-\\d{{2}}-\\d{{2}}\""
replace = "__date__ = '{now:%Y-%m-%d}'"
regex = true

[[tool.bumpversion.files]]
filename = 'tests/__init__.py'

[[tool.bumpversion.files]]
filename = 'src/robotpuzzle/__init__.py'
search = "__date__ = \"\\d{{4}}-\\d{{2}}-\\d{{2}}\""
replace = "__date__ = '{now:%Y-%m-%d}'"
regex = true

[[tool.bumpversion.files]]
filename = 'src/robotpuzzle/__init__.py'

[[tool.bumpversion.files]]
filename = 'src/robotpuzzle/node.py'

[[tool.bumpversion.files]]
filename = 'src/robotpuzzle/robots.py'

